/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Book } from '../../models/book';
import { CreateBook } from '../../models/create-book';

export interface ImportBooks$Params {
      body: Array<CreateBook>
}

export function importBooks(http: HttpClient, rootUrl: string, params: ImportBooks$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Book>>> {
  const rb = new RequestBuilder(rootUrl, importBooks.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Book>>;
    })
  );
}

importBooks.PATH = '/books/import';
