/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Book } from '../../models/book';

export interface UpdateBook$Params {
  id: number;
      body: Book
}

export function updateBook(http: HttpClient, rootUrl: string, params: UpdateBook$Params, context?: HttpContext): Observable<StrictHttpResponse<Book>> {
  const rb = new RequestBuilder(rootUrl, updateBook.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Book>;
    })
  );
}

updateBook.PATH = '/books/{id}';
