/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetBooks$Params as GetBooks$Params } from './fn/books/get-books';
export { getBooks as getBooks } from './fn/books/get-books';
export type { CreateBook$Params as CreateBook$Params } from './fn/books/create-book';
export { createBook as createBook } from './fn/books/create-book';
export type { GetBookById$Params as GetBookById$Params } from './fn/books/get-book-by-id';
export { getBookById as getBookById } from './fn/books/get-book-by-id';
export type { UpdateBook$Params as UpdateBook$Params } from './fn/books/update-book';
export { updateBook as updateBook } from './fn/books/update-book';
export type { DeleteBook$Params as DeleteBook$Params } from './fn/books/delete-book';
export { deleteBook as deleteBook } from './fn/books/delete-book';
export type { ImportBooks$Params as ImportBooks$Params } from './fn/books/import-books';
export { importBooks as importBooks } from './fn/books/import-books';
