/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Book } from '../models/book';
import { createBook } from '../fn/books/create-book';
import { CreateBook$Params } from '../fn/books/create-book';
import { deleteBook } from '../fn/books/delete-book';
import { DeleteBook$Params } from '../fn/books/delete-book';
import { getBookById } from '../fn/books/get-book-by-id';
import { GetBookById$Params } from '../fn/books/get-book-by-id';
import { getBooks } from '../fn/books/get-books';
import { GetBooks$Params } from '../fn/books/get-books';
import { updateBook } from '../fn/books/update-book';
import { UpdateBook$Params } from '../fn/books/update-book';

@Injectable({ providedIn: 'root' })
export class BooksService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getBooks()` */
  static readonly GetBooksPath = '/books';

  /**
   * List all books.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getBooks()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBooks$Response(params?: GetBooks$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Book>>> {
    const obs = getBooks(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * List all books.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getBooks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBooks(params?: GetBooks$Params, context?: HttpContext): Observable<Array<Book>> {
    const resp = this.getBooks$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<Book>>): Array<Book> => r.body)
    );
  }

  /** Path part for operation `createBook()` */
  static readonly CreateBookPath = '/books';

  /**
   * Create a book.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createBook()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBook$Response(params: CreateBook$Params, context?: HttpContext): Observable<StrictHttpResponse<Book>> {
    const obs = createBook(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Create a book.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createBook$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBook(params: CreateBook$Params, context?: HttpContext): Observable<Book> {
    const resp = this.createBook$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Book>): Book => r.body)
    );
  }

  /** Path part for operation `getBookById()` */
  static readonly GetBookByIdPath = '/books/{id}';

  /**
   * Get a single book by id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getBookById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBookById$Response(params: GetBookById$Params, context?: HttpContext): Observable<StrictHttpResponse<Book>> {
    const obs = getBookById(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get a single book by id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getBookById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBookById(params: GetBookById$Params, context?: HttpContext): Observable<Book> {
    const resp = this.getBookById$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Book>): Book => r.body)
    );
  }

  /** Path part for operation `updateBook()` */
  static readonly UpdateBookPath = '/books/{id}';

  /**
   * Replace a book by id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateBook()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBook$Response(params: UpdateBook$Params, context?: HttpContext): Observable<StrictHttpResponse<Book>> {
    const obs = updateBook(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Replace a book by id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateBook$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBook(params: UpdateBook$Params, context?: HttpContext): Observable<Book> {
    const resp = this.updateBook$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Book>): Book => r.body)
    );
  }

  /** Path part for operation `deleteBook()` */
  static readonly DeleteBookPath = '/books/{id}';

  /**
   * Delete a book by id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteBook()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBook$Response(params: DeleteBook$Params, context?: HttpContext): Observable<StrictHttpResponse<Book>> {
    const obs = deleteBook(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Delete a book by id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteBook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBook(params: DeleteBook$Params, context?: HttpContext): Observable<Book> {
    const resp = this.deleteBook$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Book>): Book => r.body)
    );
  }

}
